version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sqlnode

  webapp:
    links:
      - postgres:pgsql-server
    depends_on:
      - postgres
    build: .
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@mail.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - .:/usr/pgadmin
  #   links:
  #     - "postgres:pgsql-server"
      